export const styles = {
  title: {
    height: '10%',
  },
  timeline: {
    width: '50%',
    height: '200px',
    backgroundColor: '#ddd',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'absolute',
  },
  screen: {
    width: '20%',
    height: '80%',
    backgroundColor: '#ddd',
    overflow: 'auto',
    padding: '20px',
    position: 'absolute',
  },
  left: {
    width: '50%',
    height: '100%',
    backgroundColor: '#2b2b2b',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  right: {
    width: '50%',
    height: '100%',
    backgroundColor: '#343434',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  card: {
    position: ' absolute',
    backgroundColor: '#343434',
    cursor: 'move',
    color: '#fff',
    width: '200px',
    margin: '0 auto',
  },
};
